beer/urls.py
from django.conf.urls import url
from . import views

app_name = 'beer'

urlpatterns = [
	# /beer/
	url(r'^$', views.IndexView.as_view(), name='index'),

	# /beer/712/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

beerdjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [	
    url(r'^admin/', admin.site.urls),
    url(r'^beer/', include('beer.urls')),
]

beer/models.py
from django.db import models

class Brewery(models.Model):
	name = models.CharField(max_length=250)
	year = models.PositiveIntegerField()

	def __str__(self):
		return self.name + ', ' + str(self.year)

class Beer(models.Model):
	name = models.CharField(max_length=250)
	brewery = models.ForeignKey(Brewery, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

beer/views.py
from django.shortcuts import render, get_object_or_404
from .models import Brewery
from django.views import generic

class IndexView(generic.ListView):
	template_name = 'beer/index.html'
	context_object_name = 'all_breweries'

	def get_queryset(self):
		return Brewery.objects.all()

class DetailView(generic.DetailView):
	model = Brewery
	template_name = 'beer/detail.html'

beer/templates/beer/detail.html
<h1>{{ brewery.name }} </h1>

<p>Founded: {{ brewery.year }}</p>

<h3>List of brewery's beers:</h3>

<ul>
	{% for beer in brewery.beer_set.all %}
	<li>{{ beer.name }}</li>
	{% endfor %}
</ul>

beer/templates/beer/index.html
{% if all_breweries %}
	<h3>All breweries</h3>
	<ul>
		{% for brewery in all_breweries %}
			<li><a href="{% url 'beer:detail' brewery.id %}">{{ brewery.name }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h3>No breweries</h3>
{% endif %}